### ISSUE TITLE
Admin panel for members of Red-DiscordBot

### ISSUE THREAD

**Issue by orels1** [orels1/Red-Portal#12]

**Comment by Kowlin** [comment]
:tada:

**Comment by orels1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin-panel](https://trello.com/c/sWxplTqg/9-admin-panel)

**Comment by orels1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Views](https://trello.com/c/bNGi6Vyg/2-views)
