### ISSUE TITLE
Voting frontend

### ISSUE THREAD

**Issue by orels1** [orels1/Red-Portal#16]
A :star: system (:+1: and :-1: are too flame-generating)

**Comment by Kowlin** [comment]
Kinda interested in your thoughts behind 👍 and 👎 being flame-generating

**Comment by orels1** [comment]
I mean, it's just from a personal experience of community management. There will always be someone, who will try to abuse the system and downvote the shit out of everything, which can make people sad, even though they understand, that it's just someone being a dick.

Plus, I do not see a point in marking a cog as bad, we appreciate all the effort people put into developing new functionality for Red.

That's my thought process, if you wanted to hear it =)

Plus, the :star: system will work basically identical if I'll want to add a sorting option based on it.

**Comment by orels1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Voting functionality for repos](https://trello.com/c/yt0mRVJ8/10-voting-functionality-for-repos)
