### ISSUE TITLE
Faulty URL on Author page.

### ISSUE THREAD

**Issue by Kowlin** [orels1/Red-Portal#27]
As example, https://cogs.red/cogs/SnappyDragon18/SnappyCogs/ when clicking on the author's name it will link you to ``https://cogs.red/SnappyDragon18``. Isn't this supposed to be the GitHub page?

**Comment by orels1** [comment]
Yea, it should, thanks for that

**Comment by orels1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the author url](https://trello.com/c/M76gY8zd/20-fix-the-author-url)
