### ISSUE TITLE
List all tags and their usage

### ISSUE THREAD

**Issue by Chovin** [orels1/Red-Portal#28]
Love this feature:
![image](https://cloud.githubusercontent.com/assets/17536161/22776167/611ed3c6-eefa-11e6-9225-91a68d4a8849.png)

Would be great if there was a place to be able to see all tags like this

**Comment by orels1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Full tags list](https://trello.com/c/uX4um8Zw/21-full-tags-list)
