### ISSUE TITLE
Old cogs and GitHub link

### ISSUE THREAD

**Issue by Zephyrkul** [orels1/Red-Portal#36]
Hi, author of [NationCogs](https://cogs.red/cogs/zephyrkul/NationCogs/) here. I committed an update to my repo that removed two cogs([nationstates](https://cogs.red/cogs/zephyrkul/NationCogs/nationstates/) and [nationshards](https://cogs.red/cogs/zephyrkul/NationCogs/nationshards/)), and yet both of those cogs are still present on cogs.red. Could they be removed, and would there be a way to remove old cogs automatically when they are no longer in the repo?

Also, I notice there isn't a link anywhere in the site to this GitHub. Could one be added, or at least a link to the New Issue page for reporting bugs? Thank you.

**Comment by orels1** [comment]
Ok, yeah, the absence of auto-deletion is listed as an issue currently :) i will delete them manually now. In terms of gh link - i'll add it, yeah, good call

**Comment by orels1** [comment]
#37 - gh link

**Comment by Zephyrkul** [comment]
Thank you for the timely response, but I still see both cogs listed on my repo page, even after a full refresh.

**Comment by orels1** [comment]
yeah, I know =) I was on my way home when I answered you, I'm home now, so I'll delete those

**Comment by orels1** [comment]
Done with that, I think I'm closing this now

**Comment by Zephyrkul** [comment]
Oh, sure, sorry. Thank you very much, and thanks for the great site! Was just about to close this myself, but you beat me to it.
