### ISSUE TITLE
Support for hidden cogs

### ISSUE THREAD

**Issue by Kowlin** [orels1/Red-Portal#38]
Hidden cogs based on the ``HIDDEN`` key in the ``info.json``

**Comment by NekoTony** [comment]
+1

**Comment by orels1** [comment]
And tests 25036fa3c82afa6c64e8050132febb5ea9ecd38f

**Comment by orels1** [comment]
Done, ran some tests - seems to be working.
Need to cover it with extra tests for travis, but that's it
