### ISSUE TITLE
Repos / Cogs ordering

### ISSUE THREAD

**Issue by Twentysix26** [orels1/Red-Portal#4]
I think approved and beta repositories / cogs should take precedence over unapproved ones, both in the general view and when searching. This brings (supposedly) higher quality stuff at the top and unapproved cog authors have more motivation to get their stuff sorted out and get approved

**Comment by orels1** [comment]
Good point, i will need to break all the cogs into 3 different lists for proper randomisation for this to work tho, but I like the idea
