### ISSUE TITLE
Visual update [Design]

### ISSUE THREAD

**Issue by orels1** [orels1/Red-Portal#43]

**Comment by orels1** [comment]
Things to do

- [x] Cogs list (mainpage)
- [x] Repo page
- [x] Cog's page
- [x] Search bar (clicked)
- [x] About page
- [x] Red-DiscordBot glam page
- [x] Patreon link 💵

**Comment by orels1** [comment]
## Cogs list
![cogs](https://cloud.githubusercontent.com/assets/3798928/25560736/b7b674fc-2d64-11e7-8e8e-73f549d6cb15.png)

**Comment by orels1** [comment]
## Cog page
![cog](https://cloud.githubusercontent.com/assets/3798928/25641246/d17ca5bc-2f9b-11e7-9844-9d8e0d797353.png)

**Comment by orels1** [comment]
## Repo page
![repo](https://cloud.githubusercontent.com/assets/3798928/25641256/dba59db4-2f9b-11e7-9574-e5aa6fa81170.png)

**Comment by orels1** [comment]
[Interactive prorotype for the current state](https://xd.adobe.com/view/65936ee1-6f41-4cc1-a476-e5d9e7ff8cdd)

**Comment by orels1** [comment]
## Search
Replaces contents of the top dark bar with searchfield anywhere on the website by clicking on it or with `cmd+shift+p`

![search](https://cloud.githubusercontent.com/assets/3798928/25643077/394d1398-2fa6-11e7-84a8-efb35a113c68.png)

**Comment by orels1** [comment]
## Patreon bar
![cogs sellout](https://cloud.githubusercontent.com/assets/3798928/25643254/54bf3718-2fa7-11e7-91bb-7325fdb7beef.png)

**Comment by orels1** [comment]
## Red-DiscordBot Glam Page
![red glam](https://cloud.githubusercontent.com/assets/3798928/25643851/b3313500-2faa-11e7-97e2-0cde241bf466.png)

**Comment by orels1** [comment]
## About page
![about](https://cloud.githubusercontent.com/assets/3798928/25644094/2974cd5c-2fac-11e7-9778-b5ce35bd5776.png)

**Comment by Aeris1One** [comment]
And... Do you have an admin page or you make edit from code directly ?

**Comment by orels1** [comment]
Admin page designs won't be shown publicly

**Comment by Celemo** [comment]
So... You can't make a screen ?

2017-11-11 19:41 GMT+01:00 orels1 <notifications@github.com>:

**Comment by Aeris1One** [comment]
So... You can't make a screen (less URL) ?

**Comment by orels1** [comment]
Why should I? The updated admin page designs are not ready anyways, and I think admin backend will be its own service
