### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by jorivanee** [orels1/Red-Portal#52]
Hey, if I click the github link in the navbar or go directly to https://cogs.red/api/v1/auth/github I get redirected to the homepage immediately, I can't login.

**Comment by orels1** [comment]
Well, this thing is only to let people into the admin panel, basically and for cogs.red v3, so at it's current state - you do log in, there is just nothing there for logged in users, even an indication. sorry for confusion, it was just a thing i built pretty fast to let members of Red-DiscordBot server Staff access my admin panel

**Comment by jorivanee** [comment]
Alright, I thought it was to add a repository, how to do that then?

**Comment by orels1** [comment]
For unapproved repos list - here https://github.com/orels1/Red-Portal/issues/3

If you want to be in the "beta" or "approved" list, you need to create an issue over here https://github.com/Twentysix26/Red-Docs/issues
