### ISSUE TITLE
[Site] Not working: cogs.red/cogs/Eslyium/

### ISSUE THREAD

**Issue by Quintenvw** [orels1/Red-Portal#56]
Basically everything to do with
https://cogs.red/cogs/Eslyium/
https://cogs.red/cogs/Eslyium/Eslyium-Cogs/
doesn't work...
:D

**Comment by skeith** [comment]
Eslyium repo is abandoned, some of them cogs are on my repo now

**Comment by Quintenvw** [comment]
thanks for the reply!
